// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCimnWlUeoAkUaBLUnpcEUqK1dkArnmlRo',
    appId: '1:599630420945:web:25948e5a17fa27c8dd9ef0',
    messagingSenderId: '599630420945',
    projectId: 'unimaps-27f60',
    authDomain: 'unimaps-27f60.firebaseapp.com',
    storageBucket: 'unimaps-27f60.firebasestorage.app',
    measurementId: 'G-ZRNRLJ4S8D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfC1GbtNlJVe4pQUwKDLBq1SVhi1YLaig',
    appId: '1:599630420945:ios:1975258f1a860eecdd9ef0',
    messagingSenderId: '599630420945',
    projectId: 'unimaps-27f60',
    storageBucket: 'unimaps-27f60.firebasestorage.app',
    iosBundleId: 'com.example.unimaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfC1GbtNlJVe4pQUwKDLBq1SVhi1YLaig',
    appId: '1:599630420945:ios:1975258f1a860eecdd9ef0',
    messagingSenderId: '599630420945',
    projectId: 'unimaps-27f60',
    storageBucket: 'unimaps-27f60.firebasestorage.app',
    iosBundleId: 'com.example.unimaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCimnWlUeoAkUaBLUnpcEUqK1dkArnmlRo',
    appId: '1:599630420945:web:b9adf8bed87f53eddd9ef0',
    messagingSenderId: '599630420945',
    projectId: 'unimaps-27f60',
    authDomain: 'unimaps-27f60.firebaseapp.com',
    storageBucket: 'unimaps-27f60.firebasestorage.app',
    measurementId: 'G-S7GJC5VK70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rSK1-n8IdRZM7oFFPlA6fCHdXdhSRko',
    appId: '1:599630420945:android:0e584bc8973f06e9dd9ef0',
    messagingSenderId: '599630420945',
    projectId: 'unimaps-27f60',
    storageBucket: 'unimaps-27f60.firebasestorage.app',
  );

}